title: Akshay K. Burusa
logo: /assets/img/headshot.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a robotics and computer vision engineer with hands-on experience developing and deploying intelligent automation systems for real-world environments. My background combines research and practical engineering in robotic perception, control, and system integration. I’m passionate about building robust field-ready robotic and automation systems that combine innovation and operational reliability.  <br><br>
  <b>Professional interests</b>: Robotics, Computer vision, Control systems, Computer vision, 3D mapping, SLAM, Sensor fusion
  <br><br>
  <a href="https://www.linkedin.com/in/aks121/">View my LinkedIn profile</a> 
show_downloads: false
theme: jekyll-theme-minimal
