title: Akshay K. Burusa
logo: /assets/img/headshot.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a robotics and computer vision engineer with experience in both research and real-world deployment. I am finishing my PhD at Wageningen University, Netherlands, in the field of robotics and computer vision, addressing occlusion challenges for visual perception. I like to work at the intersection of technical innovation and real-world impact.  <br><br>
  <b>Professional interests</b>: Robotics, Computer vision, 3D scene understanding and mapping, Autonomous navigation, SLAM, and Sensor fusion
  <br><br>
  <a href="https://www.linkedin.com/in/aks121/">View my LinkedIn profile</a> 
show_downloads: false
theme: jekyll-theme-minimal
